docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login registry.gitlab.com  -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - echo '  @@@  building artefacts @@@ '
    - apk update
    - apk add openjdk17
    - apk add maven
    - sh build.sh
    - echo '  @@@  building images @@@ '
    - docker build --tag registry.gitlab.com/anderson.lopes.2010/student-management .
    - docker push registry.gitlab.com/anderson.lopes.2010/student-management  
    - echo 'done'