server:
  port: ${STUDENT_SERVER_PORT:8888}
spring:
  application:
    name: student
  sql:
    init:
      platform: postgres
  datasource:
    username: ${STUDENT_DB_USERNAME:postgres}
    password: ${STUDENT_DB_PASSWORD:root}
    url: jdbc:postgresql://${STUDENT_DB_SERVER_URL:localhost}:${STUDENT_DB_SERVER_PORT:5432}/student
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
